[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["compiler_builtins", "alloc"]
json-target-spec = true

[build]
target = "x86_64-personal_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
